//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreePlaySim.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreePlaySim.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string FootballMap {
            get {
                return ResourceManager.GetString("FootballMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;simulation&gt;
        ///  &lt;equipe nom=&quot;Paris&quot;&gt;
        ///    &lt;joueur prenom=&quot;Ezequiel&quot; nom=&quot;LAVEZZI&quot; numero=&quot;6&quot; poste=&quot;millieu&quot; position=&quot;MG&quot; /&gt;
        ///    &lt;joueur prenom=&quot;Moura&quot; nom=&quot;LUCAS&quot; numero=&quot;9&quot; poste=&quot;milieu&quot; position=&quot;MD&quot; /&gt;
        ///    &lt;joueur prenom=&quot;Zlatan&quot; nom=&quot;IBRAHIMOVIC&quot; numero=&quot;10&quot; poste=&quot;attaquant&quot; position=&quot;BU&quot;/&gt;
        ///    &lt;joueur prenom=&quot;Gregory&quot; nom=&quot;WAN DER WIEL&quot; numero=&quot;4&quot; poste=&quot;defenseur&quot; position=&quot;DD&quot;/&gt;
        ///    &lt;joueur prenom=&quot;Lucas&quot; nom=&quot;DIGNE&quot; numero=&quot;3&quot; poste=&quot;defenseur&quot; positi [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string footballSimulation {
            get {
                return ResourceManager.GetString("footballSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SimulationWar&gt;
        ///  &lt;armee nom=&quot;A&quot;&gt;
        ///    &lt;personnage nom=&quot;VERRATTI&quot; type=&quot;Princesse&quot; /&gt;
        ///    &lt;personnage nom =&quot;BAHEBECK&quot; type=&quot;Archer&quot;/&gt;
        ///    &lt;personnage nom=&quot;VAN DER WIEL&quot; poste=&quot;Cavalier&quot;/&gt;
        ///  &lt;/armee&gt;
        ///  &lt;armee nom =&quot;B&quot;&gt;
        ///    &lt;personnage nom =&quot;MENDY&quot; poste=&quot;Princesse&quot; /&gt;
        ///    &lt;personnage nom=&quot;PAYET&quot; poste=&quot;Fantassin&quot; /&gt;
        ///    &lt;personnage nom=&quot;GIGNAC&quot; poste=&quot;Cavalier&quot; /&gt;
        ///  &lt;/armee&gt;
        ///&lt;/SimulationWar&gt;
        ///.
        /// </summary>
        internal static string SimulationWar {
            get {
                return ResourceManager.GetString("SimulationWar", resourceCulture);
            }
        }
    }
}
